######################################################################
# Automatically generated by qmake (3.1) Thu Jun 1 00:48:04 2017
######################################################################

TEMPLATE = app
TARGET = mi1e4r
QT += widgets core gui
INCLUDEPATH += .

# Input
SOURCES += main.cpp
